### PR TITLE
Database implementation, GUI updates and refactoring

### LINKED ISSUE #56: Create graphic for joystick background
Create and add a drawable background to the joystick that visually represents the corresponding commands that will be sent to the SmartCar.

# Acceptance Criteria
The joystick has an informative background that follows the visual theme of the application while also providing infromation to the user.

### LINKED ISSUE #59: Update icon
The current icon of the Android Application follows the [Android Icon Design Specification](https://developer.android.com/google-play/resources/icon-design-specifications) but not the [Material Design Guidelines](https://material.io/design/iconography/product-icons.html#design-principles) recommended in previous specification.
Update icon to follow the material design guidelines as well.

# Ideas to consider: 
- Reduce detail level in the icon, it currently has three distinct elements each with its own details.
- Add drop shadow/elevation to lift graphic off of background, similar to how the Android Application currently elevates popups.
- Remove the plus-sign signifying "healthcare" and go with the two main themes; drivable car with wifi-connectivity.

# Acceptance Criteria
- Icon follows the [Android Icon Design Specification](https://developer.android.com/google-play/resources/icon-design-specifications)
- Icon follows the [Material Design Guidelines](https://material.io/design/iconography/product-icons.html#design-principles)

### LINKED ISSUE #79: Change SmartCar name
# User Story: 

- As a medical professional I want to be able to change the name of the SmartCar so that I can customize my favorite one.

# Acceptance criteria:
The user is provided with an option to change the name of the SmartCar.
When the user enters the new name of the SmartCar, the car select list and the information on all corresponding pages is updated accordingly to reflect the change.

### LINKED ISSUE #80: Save updates into persistent storage
# User Story: 

- As a medical professional I want the application to be able to save changes/updates that I made So that next time when I start the application I don't have to do them again. 

# Acceptance criteria:
A Persistent storage is integrated with the application. 
The application supports the basic CRUD functionalities.
The application is able to load the data on start.

### PR DESCRIPTION
**Pull request by chrytsa**
# Related issues
- Closes #56, closes #59, helps #61, closes #79, closes #80

# Proposed changes
- Transition from using Enums for the car(s) representations in the backend, to car objects.
- Added database implementation in the codebase, in order to be able to read, write, and update information related to the car objects.
- Codebase refactoring that was needed for the aforementioned transition.
- GUI updates:
  - Addition of "edit" button in the Car Select menu, so that the user can edit the name of the car(s).
  - Update of the logo and the background image of the joystick

# Additional information
- Addition of automated tests

### CODE REVIEW

**Review by krasen86 — APPROVED** [review]
Looks nice, I added some unit tests for the database and we can continue adding more. I am going to add a note to #61 to add some more tests for the carManagement implementation class since that one needs aditional testing.

**Comment by krasen86** [comment]
Apparently Travis timeout causes the build to fail. All the tests are passing locally. It is ok to merge to dev-branch. Working on finding a way to increase the wait for the instrumentet tests.

**Comment by platisd** [comment]
Why have a dev branch in the first place? 😓😩

**Comment by krasen86** [comment]
We like our dev branch, It keeps the master safe, and let us sleep in peace  :)

**Pull request merged**
