### PR TITLE
Refactor user interface

### PR DESCRIPTION
**Pull request by SandraSmolerEisenberg**
# Related issue
- #60 

# Proposed changes
- Refactor:
     - Variable names to follow project naming conventions.
     - Strings moved to strings.xml.
     - Colors moved to colors.xml.
     - Increase use of style recources to reduce duplicate code.
     - Create utility class to handle popup and toast creations for reduced redundancy.
     - Remove unused strings and imports.
- Add info button with credits.

### CODE REVIEW

**Comment by krasen86** [comment]
The Travis build cannot run before the merge conflicts are resolved. Do you want me to resolve it manually here or you want fix it on your local version?

**Comment by SandraSmolerEisenberg** [comment]
We have checked the conflicts and they are no problem.
Our commit should be accepted in the first one, CarSelect. And in the other one, strings.xml, both commits should be included. We just wanted you guys to review if you wanted before we merge it ourselves

**Comment by krasen86** [comment]
There are currently 2 conflicts that prevent the CI build and prevent the merge.

**Review by chrytsa — CHANGES_REQUESTED** [review]
There is an exception causing the gradle build to fail, due to a missing import according to the stacktrace (`import android.widget.Toast`) in CarSelect class (it couldn't recognize `Toast.makeText(this, errorMessage, Toast.LENGTH_LONG).show();` at line `93`)

**Comment by chrytsa** [comment]
Nice good job! :+1: :relaxed:

**Pull request merged**
