### PR TITLE
Factory and test

### PR DESCRIPTION
**Pull request by krasen86**
# Related issue
- #60 and #61 

# Proposed changes
- Add a simple static stub web server for testing
- Update the factory pattern in order to inject the stub webServer
- Add automated tests for the CarSelect page

### CODE REVIEW

**Comment by krasen86** [comment]
Apparently there is an issue with Travis and instrumented test when we need to verify the popup window text. We were forced to comment out test_case 3 in CarSelect test in order to build and run the tests in Travis. The test runs fine and passes when you run it on local emulator. There is an issue with the way Travis treats pop-up windows in relationship with the root screen. The test needs to be rewritten or we need to find a solution for the Travis set-up.

**Comment by chrytsa** [comment]
First of all, I could also verify that indeed the tests pass perfectly fine _locally_. I even changed the emulator using the `armeabi-v7a` Instruction Set, with the tests still passing.

Secondly, do we actually need to include `inRoot(RootMatchers.isPlatformPopup())` in line `120` of `CarSelectTest` that obviously is the root of the problem (in Travis side at least)? Because I tested it without it and it passes the TravisCI check in a private repository. I don't think that it affects entirely the logic of the test, so that might be a worth-looking workaround?

Lastly, while giving it more time to test how to circumvent that issue, I tried to alter .travis.yml file and re-run the tests based on the following changes (among other configuration changes as well), adding them at before_screen section, without any luck:
```
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &
```

So, all in all, in order to not having them commented out, basically we could change the aforementioned line to that: `onView(withId(R.id.infoPopup)).check(matches(isDisplayed()));`

**Comment by krasen86** [comment]
Yes I agree that will not change the verification in the pop-up. Can you commit the updated test?

**Comment by chrytsa** [comment]
Alright, the TravisCI check has passed without any errors, but since I commited last and in order to be inline with the logic of reviews, it would be wiser either someone else to approve it, or just comment if you agree with the last commit so I can approve it.

**Review by samgun-6 — APPROVED** [review]

**Pull request merged**
